name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - name: run eslint
        run: yarn lint
      - name: run jest
        run: yarn jest
